version: '2'

services:
  web:
    ports:
      - 81:80
    extra_hosts:
      - "phpstorm:${PHPSTORM_HOST_IP}"

  db:
    ports:
      - 3306:3306

  datastore:
    ports:
      - 8081:8081
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud

  phpmyadmin:
    build: phpmyadmin
    depends_on:
      - db
    links:
      - db
    env_file: .env
    ports:
      - 8080:80
