version: '2'

services:
  api:
    image: $WEB_IMAGE
    volumes:
      - ..:/var/www
    environment:
      LOCAL_USER_ID: 0
    depends_on:
      - db
      - datastore
    links:
      - db
      - datastore

  db:
    image: $MYSQL_IMAGE
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ravenlocal

  datastore:
    image: $DATASTORE_IMAGE
    env_file: .env
    environment:
      DATASTORE_PROJECT_ID: $CLOUD_ACCOUNT
      DATASTORE_LISTEN_ADDRESS: 0.0.0.0:8081
